name: AppImage Build

on:
  [workflow_dispatch]

jobs:
  build-appimage:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    
    - name: Build Cascade
      run: | 
        cd scripts
        sh install-deps.sh 
        cd ..
        qmake
        make -j4
        cd
     
    - name: Prepare AppDir
      run: |
        mkdir CascadeExtra
        cd CascadeExtra
        git config --global init.defaultBranch main
        git init
        git remote add -f origin https://github.com/ttddee/CascadeExtra
        git config core.sparseCheckout true
        echo "Cascade.AppDir" >> .git/info/sparse-checkout
        git pull origin main
        cd
        ls /home/runner/work/Cascade/Cascade/release
        cp /home/runner/work/Cascade/Cascade/release/Cascade /home/runner/work/Cascade/Cascade/CascadeExtra/Cascade.AppDir/Cascade
     
    - name: Build AppImage
      run: |
        wget https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage
        chmod +x linuxdeployqt-continuous-x86_64.AppImage
        ./linuxdeployqt-continuous-x86_64.AppImage /home/runner/work/Cascade/CascadeExtra/Cascade.AppDir/usr/share/applications/Cascade.desktop -verbose=2 -no-translations -appimage -always-overwrite
        git_hash=$(git rev-parse --short "$GITHUB_SHA")
        mv Cascade-x86_64.AppImage Cascade-Image-Editor-x86_64-dev-${git_hash}.AppImage
          
    - name: Prepare upload
      run: |
        mkdir downloads
        cp Cascade-Image* downloads
          
    - uses: actions/upload-artifact@v3
      with:
        name: appimage
        path: downloads
          
        
         
            
