name: Windows Build

on:
  [push , pull_request]

jobs:
  build-windows:

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v3
    
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        arch: win64_msvc2019_64
        setup-python: false
      
    - name: Install Vulkan SDK
      uses: humbletim/setup-vulkan-sdk@v1.2.0
      with:
        vulkan-query-version: 1.2.198.1
        vulkan-components: Vulkan-Headers, Vulkan-Loader
        vulkan-use-cache: true
      
    - uses: friendlyanon/setup-vcpkg@v1
        with: { committish: 63aa65e65b9d2c08772ea15d25fb8fdb0d32e557 }
      
    - name: Install vcpkg packages
      run: |
        .\vcpkg\vcpkg --feature-flags="versions" --triplet=x64-windows  install
        
    - uses: ilammy/msvc-dev-cmd@v1
        
    - name: Build
      run: |
        qmake
        make -j4
