name: Tests

on:
  push:
    branches: '*'
    
  pull_request:
    branches: '*'
    
  workflow_dispatch:

jobs:
  run-tests:
  
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - uses: actions/cache@v3
      id: cache-deps
      with:
        path: external
        key: ${{ runner.os }}-deps-${{ hashFiles('scripts/install_deps.sh') }}

    - name: Build dependencies
      if: steps.cache-deps.outputs.cache-hit != 'true'
      run: | 
        cd scripts
        sh install-deps.sh 
        cd ..
    
    - name: Install packages
      #if: steps.cache-deps.outputs.cache-hit == 'true'
      run: | 
        sudo apt install -y libopenimageio-dev libgtest-dev google-mock libtbb-dev build-essential qtbase5-dev qt5-qmake qtbase5-dev-tools libopenexr-dev cmake libglew-dev freeglut3-dev '^libxcb.*-dev' libx11-xcb-dev libglu1-mesa-dev libxi-dev libxkbcommon-dev libxkbcommon-x11-dev libxcb-xinerama0-dev libx11-xcb-dev

    - name: Set up Googletest
      run: |
        cd /usr/src/gtest
        sudo cmake CMakeLists.txt
        sudo make -j4
        cd
        
    - name: Set up Googlemock
      run: |
        cd /usr/src/gmock
        sudo cmake CMakeLists.txt
        sudo make -j4
        cd

    - name: Run Tests
      run: | 
        #export GTEST_SRCDIR=/usr/src/gtest/src
        #export GMOCK_SRCDIR=/usr/src/gmock/src
        cd test/CascadeTests
        qmake
        make -j4
        ls
        ./CascadeTests
